<body>
    <header>
        <nav style="height: 55px;" class="navbar navbar-expand-lg" id="contenidoDinamico">
            <div class="container">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="font-size: 14px; color: white;">DIP</a>
                    </li>
                    <li class="nav-item">
                        <div class="nav-link" style="font-size: 14px; color: white;">|</div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="font-size: 14px; color: white;">Transformación Digital</a>
                    </li>
                    <li class="nav-item">
                        <div class="nav-link" style="font-size: 14px; color: white;">|</div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="font-size: 14px; color: white;">Ley del Lobby</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ul-nav-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="color: white;"><i class="bi bi-instagram"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-twitter-x" style="color: white;"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="color: white;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-facebook">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3" />
                            </svg></a>
                    </li>
                    <li class="nav-item">
                        <a style="color: white;" class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-flickr">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M7 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                                <path d="M17 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                            </svg></a>
                    </li>
                    <li class="nav-item">
                        <a style="color: white;" class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-youtube">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M2 8a4 4 0 0 1 4 -4h12a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-12a4 4 0 0 1 -4 -4v-8z" />
                                <path d="M10 9l5 3l-5 3z" />
                            </svg></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="bordeColores" style="width: 100%;">
        <div>
            <nav style="background-color: white;" class="container navbar navbar-expand-lg nav2">
                <div>
                    <div class="menuDinamico" style="display: flex; align-items: start; text-align: start; justify-content: start;">
                        <div>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                                aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="marca4">
                        <a href="https://intranet.imaarica.cl/"><img style="width: 300px; margin-left: -10px;" class="img-nav" src="../recursos/img/marca 4.png" alt=""></a>
                    </div>
                </div>
                <div class="collapse navbar-collapse contenidoMenuDinamico" id="navbarNavAltMarkup" style="justify-content: end;">
                    <div class="navbar-nav" style="align-items: start; text-align: start; margin-right: -25px;">
                        <div class="navbar-nav">
                            <a style="color: #6c7a91; width: 110px;" class="nav-link " aria-current="page" href="#"> <svg
                                    xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                    viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round"
                                    class="icon icon-tabler icons-tabler-outline icon-tabler-device-landline-phone">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path
                                        d="M20 3h-2a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h2a2 2 0 0 0 2 -2v-14a2 2 0 0 0 -2 -2z" />
                                    <path d="M16 4h-11a3 3 0 0 0 -3 3v10a3 3 0 0 0 3 3h11" />
                                    <path d="M12 8h-6v3h6z" />
                                    <path d="M12 14v.01" />
                                    <path d="M9 14v.01" />
                                    <path d="M6 14v.01" />
                                    <path d="M12 17v.01" />
                                    <path d="M9 17v.01" />
                                    <path d="M6 17v.01" />
                                </svg> Anexos</a>

                            <a style="color: #6c7a91; width: 110px;" class="nav-link" href="#"><svg
                                    xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                    viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round"
                                    class="icon icon-tabler icons-tabler-outline icon-tabler-device-mobile">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path
                                        d="M6 5a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-14z" />
                                    <path d="M11 4h2" />
                                    <path d="M12 17v.01" />
                                </svg> Celulares</a>

                            <a style="color: #6c7a91; width: 110px;" class="nav-link" href="#"><svg
                                    xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                    viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round"
                                    class="icon icon-tabler icons-tabler-outline icon-tabler-info-circle">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" />
                                    <path d="M12 9h.01" />
                                    <path d="M11 12h1v4h1" />
                                </svg> Contacto</a>

                            <a style="color: #6c7a91; width: 110px;" href="#" class="nav-link">Kit Digital</a>
                        </div>

                        <div>

                        </div>
                        <div class="buttonRRHH" style="margin-bottom: 5px; margin-right: 7px;">
                            <button style="width: 100%;"><a class="nav-link" href="https://intranetarica.smc.cl/login.aspx"><svg xmlns="http://www.w3.org/2000/svg"
                                        width="24" height="24" viewBox="0 0 24 24" fill="none"
                                        stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round"
                                        class="icon icon-tabler icons-tabler-outline icon-tabler-users">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M9 7m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" />
                                        <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                                        <path d="M16 3.13a4 4 0 0 1 0 7.75" />
                                        <path d="M21 21v-2a4 4 0 0 0 -3 -3.85" />
                                    </svg> Sistema RR.HH</a></button>
                        </div>

                        <div class="buttonBuscar">

                            <div>
                                <button id="buttonBuscarPequeño" class="contenidoBtnBuscar"><a style="color: #6c7a91;" class="nav-link" href="#"><svg
                                            xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                            viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                            stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                            class="icon icon-tabler icons-tabler-outline icon-tabler-search">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                            <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" />
                                            <path d="M21 21l-6 -6" />
                                        </svg></a></button>
                            </div>

                            <div style="width: 100%; margin-top: 5px; margin-right: 7px;">
                                <button id="buttonBuscarDinamico" style="width: 100%;" class="contenidoBtnBuscarDinamico"><a style="color: #6c7a91;" class="nav-link" href="#"><svg
                                            xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                            viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                            stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                            class="icon icon-tabler icons-tabler-outline icon-tabler-search">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                            <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" />
                                            <path d="M21 21l-6 -6" />
                                        </svg></a>Buscar Documentos</button>
                            </div>

                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div>
        <div class="contenedor-titular">
            <div class="container nombre-seccion-titular">
                <div class="container titulo-seccion">
                    <h2 style="padding-bottom: 35px; margin: -10px;">Generador De Firmas Municipales</h2>
                    <img style="margin: -25px; width: 21.5%; padding-bottom: 25px; padding-top: 25px;" src="../recursos/img/en_blanco-03.png" alt="Logo Municipalidad de Arica en Blanco">
                </div>
            </div>
        </div>
    </div>
    <!-- Sección principal -->
    <main>
        <header style="margin-top: 2%; margin-bottom: 2%;" class="container container-fluid d-flex">
            <div class="container">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Mostrar video tutorial
                </button>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered " style="max-width: 1000px;" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Video Tutorial</h5>
                        </div>
                        <!-- Video Tutorial -->
                        <div class="modal-body d-flex justify-content-center align-items-center">
                            <video style="width: 95%; height: auto;" controls>
                                <source src="../recursos/vid/videoTutorialFirma.mkv" type="video/mp4">
                                Tu navegador no soporta el elemento.
                            </video>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container" style="display: flex; justify-content: end;">
                <div>
                    <a href="../index.html" class="btn btn-primary btnVolverHome">Volver al Kit Digital</a>
                </div>
            </div>
        </header>
        <div class="container container3">
            <h4>Instrucciones</h4>
            <ol>
                <li>Completar el formulario con los datos solicitados.</li>
                <li>Una vez ingresados los datos, se deberá descargar la firma ubicada a un costado del formulario. Para realizar esto, se generó un botón de descarga <i class="bi bi-download"></i> , el cual se encuentra a la derecha de la firma generada. <br>
                    *En caso de no ingresar un dato adicional, simplemente descargar la firma con los datos necesarios*
                </li>
                <li>Luego se deberá continuar en la sección de configuración de su correo electrónico.</li>
                <li>Ubicar la sección de 'Firma'.</li>
                <li>Generar una nueva firma dando clic en el botón 'Crear'.</li>
                <li>Asignar un nombre a la firma, luego seleccionar la opción 'Insertar imagen' ubicada en la barra inferior del espacio para agregar firmas.</li>
                <li>En la parte superior ubicar la opción 'Google Drive', luego en la seccion izquierda seleccionar la opción 'Subir'.</li>
                <li>Agregar imagen de firma previamente descargada.</li>
                <li>Seleccionar 'Permitir'.</li>
                <li>Finalmente, en la parte inferior de la página de configuración de su correo electrónico, dar clic en 'Guardar cambios'.</li>
            </ol>
        </div>
        <div class="contenedorPrincipalFirmas container">
            <form class="container container2 p-4">
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="nombre" placeholder="Ingresar nombre completo" oninput="updateFirma()"> <!-- Aplicamos la función updateFirma a la acción oninput para lograr imprimir los datos al momento que el usuario los agregue en el formulario -->
                </div>
                <div class="mb-3">
                    <label for="cargo" class="form-label">Cargo</label>
                    <input type="text" class="form-control" id="cargo" placeholder="Ingresar cargo" oninput="updateFirma()"> <!-- Repetimos oninput="updateFirma()" en cada input -->
                </div>
                <div class="mb-3">
                    <label for="unidad" class="form-label">Unidad</label>
                    <input type="text" class="form-control" id="unidad" placeholder="Ingresar unidad/departamento al que pertenece" oninput="updateFirma()">
                </div>
                <div class="mb-3">
                    <label for="anexo" class="form-label">Anexo</label>
                    <input type="text" class="form-control" id="anexo" placeholder="Ingresar anexo completo" oninput="updateFirma()">
                </div>
                <div class="mb-3">
                    <label fo-r="anexo" class="form-label">Dato Adicional (Opcional)</label>
                    <input type="text" class="form-control" id="adicional" placeholder="Dato adicional opcional" oninput="updateFirma()">
                </div>
            </form>

            <div style="width: 80%; position: relative; overflow: hidden;">
                <div class="firma-container" id="firma-container" style="position: relative; overflow: auto; word-wrap: break-word;">
                    <table>
                        <tr>
                            <td style="overflow: hidden; text-overflow: ellipsis;">
                                <img src="../recursos/img/plantillaFirmaMunicipal.png" alt="Firma" class="firma-image">
                            </td>
                            <td class="firma-details" style="overflow: hidden; text-overflow: ellipsis;"> <!-- Mediante text-overflow: ellipsis lograremos que la información no salga del contenedor de la firma si es que llegase a tener muchos caracteres -->
                                <span id="firma-nombre">Nombre</span><br>
                                <span id="firma-cargo">Cargo</span><br>
                                <span id="firma-unidad">Unidad</span><br>
                                <span id="firma-anexo">Anexo</span><br>
                                <span id="dato_adicional">Adicional</span><br>
                            </td>
                        </tr>
                    </table>
                    <div class="botonCopiarFirma" style="position: absolute; top: 0; right: 10px;">
                        <button id="capturar-btn" class="btn btn-primary"><i class="bi bi-download"></i></button>
                    </div>
                </div>
            </div>

        </div>
    </main>
</body>