<div class="topbar py-1">
    <div class="container d-flex justify-content-between small pt-3 pb-3">
        <div>
            <a href="https://intranet.imaarica.cl/page/dip" class="me-2">DIP</a>
            <span class="text-white">|</span>
            <a href="https://intranet.imaarica.cl/page/transformacion-digital" class="mx-2">Transformación Digital</a>
            <span class="text-white">|</span>
            <a href="https://intranet.imaarica.cl/page/ley-del-lobby" class="ms-2">Ley del Lobby</a>
        </div>
        <div>
            <a href="https://www.instagram.com/muniarica/" class="text-white me-2" aria-label="Instagram"><i class="bi bi-instagram"></i></a>
            <a href="https://www.facebook.com/MunicipalidaddeArica" class="text-white me-2" aria-label="Facebook"><i class="bi bi-facebook"></i></a>
            <a href="https://www.flickr.com/photos/muniarica/" class="text-white me-2" aria-label="Flickr"><i class="bi bi-camera"></i></a>
            <a href="https://www.youtube.com/@CanalMunicipalidadArica" class="text-white" aria-label="YouTube"><i class="bi bi-youtube"></i></a>
            <a href="https://www.tiktok.com/@aricamunicipalidad" class="text-white" aria-label="Tiktok"><i class="bi bi-tiktok"></i></a>
            <a href="https://open.spotify.com/user/31afurm6j5wkukrjpmjqx7oj5z7y" class="text-white" aria-label="Spotify"><i class="bi bi-spotify"></i></a>
        </div>
    </div>
</div>