<footer style="background-color: #1c1c1c; padding: 0; text-align: center;">
    <img src="<?= $this->basePath('public/img/footer-ilustracion.png') ?>" alt="footer-ilustracion" style="width: 100%; height: auto; display: block;">
    <div style="height: 2rem; width: 100%; background-color: #06048c;"></div>
    <div class="container py-3">
        <div class="text-white-50 small">
            &copy; <?= date('Y') ?> DIDECO - Ilustre Municipalidad de Arica
        </div>
    </div>
</footer>